appli/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', login_required(views.home), name='home'),
    url(r'^accounts/login', auth_views.login, {'template_name': 'auth/connexion.html'}, name='login'),
    url(r'^accounts/profile/$', login_required(views.profile), name='profile'),
    url(r'^accounts/logout$', auth_views.logout, {'next_page': 'home'},name='logout'),
    
    url(r'^about/statistics$', login_required(views.statistics), name='statistics'),
]

poc_sport/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views
from .models import Exercice

urlpatterns = [
    url(r'home$' , login_required(views.exerciceHome), name='exercice_home'),
    url(r'exercice/new$', login_required(views.ExerciceCreate.as_view()), name='exercice_create'),
    url(r'exercice/edit/(?P<pk>\d+)$', login_required(views.ExerciceUpdate.as_view()), name='exercice_update'),
    url(r'exercice/delete/(?P<pk>\d+)$', login_required(views.ExerciceDelete.as_view()), name='exercice_delete'),
    url(r'graph$', views.graph, name='exercice_graph'),
]

poc_sport/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User

import numpy as np

class Exercice(models.Model):
    date = models.DateField(default=datetime.date.today)
    exercices = (('ventre','Ventre'),('cote_gauche','cote gauche'),('cote_droit','cote droit'),)
    exercice = models.CharField(max_length=20,choices=exercices)
    temps_qt = models.DurationField(null=True, blank=True)
    temps_db = models.DurationField(null=True, blank=True)
    
    class Meta:
        ordering = ['date']        
    
    def get_temps_total_by_date(self):
        temps_qt = 0
        temps_db = 0
        for exercice in Exercice.objects.filter(date=self.date):
            temps_qt += exercice.temps_qt
            temps_db += exercice.temps.db
        return {'qt': temps_qt, 'db':temps_db}
    
    def get_list_values():
        tableau = []
        for jour in Exercice.objects.values_list('date', flat=True).distinct():
            qt_total=0
            db_total=0
            for exercice in Exercice.objects.filter(date=jour):
                qt_total += exercice.temps_qt.total_seconds()
                db_total += exercice.temps_db.total_seconds()
            tableau.append([db_total, qt_total])
                    
        return tableau

poc_sport/forms.py
from django import forms
from .models import Exercice

class ExerciceForm(forms.ModelForm):
    class Meta:
        model = Exercice
        fields = '__all__'

notes/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views.generic import ListView,CreateView,DetailView,UpdateView,DeleteView, FormView
from django.core.urlresolvers import reverse_lazy
from .models import Notes, Category, Bookmark, NotesFile, Community, CommunityUsers
from .forms import NotesForm, CategoryForm, BookmarkForm, PartialBookmarkForm, CommunityForm, CommunityUsersForm
from django.views.decorators.csrf import csrf_exempt
from reportlab.pdfgen import canvas
from django.http import HttpResponse
from django.db.models import Q
from django.forms import modelformset_factory
from django.conf import settings

"""
Notes
"""

def notesList(request):
    #communities = Community.objects.filter((Q(community_users=request.user) & Q(communityusers__user_visa=True)) | Q(owner=request.user)).distinct()
    community_list = Community.get_communities_by_user(request.user)
    all_communities_list = CommunityUsers.get_all_communities_by_user(request.user)
    # TODO : check if user_visa == True
    #notes_list = Notes.objects.filter((Q(category__community__communityusers__user=request.user) & Q(category__community__communityusers__user_visa = True))| Q(category__community__owner=request.user)).distinct()
    notes_list = Notes.objects.filter(category__in=Category.get_subcategories_by_user(request.user))
    return render(request, 'notes/notes_list.html', locals())



def notesCreateOrUpdate(request, category_id, notes_id=None):
    community_list = Community.get_communities_by_user(request.user)
    category = Category.objects.get(id=category_id)
    if notes_id:
        note_to_edit = Notes.objects.get(id=notes_id)
        # Check if the user has the rights to edit that note
        if not note_to_edit.can_user_see(request.user):
            messages.info(request, 'You dont have the rights to edit that note')
            return redirect('notes_list')
        upfiles = note_to_edit.notesfile_set.all()
    else:
        note_to_edit = None
    form = NotesForm(request.POST or None,request.FILES or None, instance=note_to_edit)
    files = request.FILES.getlist('uploaded_files')
    if form.is_valid():
        note = form.save(commit=False)
        if not hasattr(note, 'owner'):
            note.owner = request.user
        if note.category == None:
            note.category = category
        note.save()
        for upfile in files:
            # QT : f.name should give the original name
            #f = NotesFile(notes=note, uploaded_file=upfile)
            f = NotesFile(notes=note, uploaded_file=upfile, original_name=upfile.name)
            f.save()
        return redirect('topic_view', category_id=note.category.id)
    return render(request,'notes/notes_create_form.html',locals())


# Ajax call of the note form
def loadNotesForm(request, category_id, notes_id=None):
    category = Category.objects.get(id=category_id)
    if notes_id:
        note_to_edit = Notes.objects.get(id=notes_id)
        upfiles = note_to_edit.notesfile_set.all()
    else:
        note_to_edit = None
    form = NotesForm(request.POST or None,request.FILES or None, instance=note_to_edit)
    return render(request, 'notes/snippet_form_note.html', locals())


def notesDelete(request, notes_id):
    notes_to_delete = Notes.objects.get(id=notes_id)
    community_list = Community.get_communities_by_user(request.user)
    if request.method == 'POST':
        # Deletion of all the physical files
        for notes_file in NotesFile.objects.filter(notes=notes_to_delete):
            notes_file.delete_physical_file()
        notes_to_delete.delete()
        messages.success(request, 'Notes "{}" deleted !'.format(notes_to_delete.title))
        return redirect('topic_view', category_id=notes_to_delete.category.id)
    return render(request, 'notes/notes_delete.html', locals())


"""
NotesFile
"""
# Ajax call (csrf disabled...probably not the right thing to do)
@csrf_exempt
def notesFileDelete(request, notes_file_id):
    file_to_delete = NotesFile.objects.get(id=notes_file_id)
    if file_to_delete:
        if not file_to_delete.delete_physical_file():
            messages.warning(request, 'problem during physical deletion...')
        else:
            messages.success(request, 'File "{}" deleted !'.format(file_to_delete.original_name))
            file_to_delete.delete()
    
    return redirect('topic_view', category_id=file_to_delete.notes.category.id)

"""
media File

def mediaFileView(request, file_path):
    #note = NotesFile.objects.get(id=notes_file_id)
    #media = note.uploaded_file.url
    response = HttpResponse()
    #response = HttpResponse('http://media.heimdall/notes/'+file_path, content_type='application/pdf')
    response['Content-Type'] = 'application/pdf'
    #response['X-Sendfile'] = 'http://media.heimdall/media/notes/'+file_path
    #response['X-Sendfile'] = 'https://media.dev.quentin-david.ovh/notes/'+file_path
    response['X-Sendfile'] = 'media/notes/34-bFxa9xefx83xafxc9x01x9ex08pxb3x08xa1TZx08xbbVx9dxd4xbcxb6xa0x8fxbaxf1xe9Qxf9yxd0'
    #response['Content-Disposition'] = 'inline; filename="{}"'.format(file_path)
    return response
"""



"""
Categories
"""
def categoryList(request, category_id=None):
    community_list = Community.get_communities_by_user(request.user)
    all_communities_list = CommunityUsers.get_all_communities_by_user(request.user)
    #personal_communities = Community.objects.filter(owner=request.user)
    #shared_communities = CommunityUsers.objects.filter(user=request.user)
    if category_id:
        category_to_edit = Category.objects.get(id=category_id)
    else:
        category_to_edit = None
    form = CategoryForm(None, instance=category_to_edit, user=request.user)
    return render(request, 'category/category_list.html', locals())


def categoryCreateOrUpdate(request, category_id=None):
    if category_id:
        category_to_edit = Category.objects.get(id=category_id)
    else:
        category_to_edit = None
    form = CategoryForm(request.POST, instance=category_to_edit)
    if form.is_valid():
        category = form.save(commit=False)
        # Sub categories have the same community as their parents
        if category.parent:
            category.community = Category.objects.get(name=category.parent).community
        else:
            # if no community is given, the default is the personal community (perso-*)
            if category.community == None:
                category.community = Community.objects.get(name='perso-'+request.user.username)
            # change it's subcategories community as well
        subcategory_list = category.category_set.all()
        if subcategory_list:
            for subcat in subcategory_list:
                subcat.community = category.community
                subcat.save()
        category.save()
        return redirect('category_list')
    return render(request, 'category/category_list.html', locals())


def categoryDelete(request, category_id):
    community_list = Community.get_communities_by_user(request.user)
    category_to_delete = Category.objects.get(id=category_id)
    if request.method == 'POST':
        category_to_delete.delete()
        return redirect('category_list')
    return render(request, 'category/category_delete.html', locals())
    
"""
Bookmark
"""
def bookmarkCreate(request, category_id=None):
    form = BookmarkForm(request.POST or None)
    if form.is_valid():
        bookmark = form.save(commit=False)
        bookmark.owner = request.user
        if category_id:
            bookmark.category = Category.objects.get(id=category_id)
        bookmark.save()
        return redirect('topic_view', category_id=bookmark.category.id)
    return render(request, 'bookmark/bookmark_list.html', locals())


def bookmarkList(request):
    community_list = Community.get_communities_by_user(request.user)
    all_communities_list = CommunityUsers.get_all_communities_by_user(request.user)
    category_list = Category.get_root_categories_by_user(request.user)
    bookmark_form = BookmarkForm(None, user=request.user)

    return render(request, 'bookmark/bookmark_list.html', locals())


def bookmarkDelete(request, bookmark_id):
    bookmark_to_delete = Bookmark.objects.get(id=bookmark_id)
    if bookmark_to_delete:   
        bookmark_to_delete.delete()
    messages.success(request, 'Bookmark "{}" deleted !'.format(bookmark_to_delete.url))
    return redirect('topic_view', category_id=bookmark_to_delete.category.id)

"""
Topic
list every elements (Notes, bookmarks...) by category
"""
def topicView(request, category_id):
    category = Category.objects.get(id=category_id)
    if not category.can_user_see(request.user):
        messages.info(request, 'You dont have the rights to see that category')
        return redirect('notes_list')
    
    community_list = Community.get_communities_by_user(request.user)
    all_communities_list = CommunityUsers.get_all_communities_by_user(request.user)
    community_user = CommunityUsers.objects.filter(user=request.user, community=category.community)
    bookmark_list = Bookmark.objects.filter(category=category.id)
    bookmark_form = PartialBookmarkForm(None)
    form = NotesForm(None)
    notes_list = Notes.objects.filter(category=category)
    
    return render(request, 'topic/topic_view.html', locals())


"""
Community
"""
def communityCreateOrUpdate(request, community_id=None):
    CommunityUsersFormFormset = modelformset_factory(CommunityUsers, form=CommunityUsersForm, exclude=('community',), extra=1)    
    if community_id:
        community_to_edit = Community.objects.get(id=community_id)
        community_users_form = CommunityUsersFormFormset(request.POST or None, queryset=CommunityUsers.objects.filter(community=community_to_edit))
    else:
        community_to_edit = None
        community_users_form = CommunityUsersFormFormset(request.POST or None, queryset=CommunityUsers.objects.none())

poc_sport/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import ListView,CreateView,DetailView,UpdateView,DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Exercice
from .forms import ExerciceForm

import pandas as pd
import numpy as np
from pandas import DataFrame
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
from matplotlib.dates import DateFormatter

def exerciceHome(request):
    exercice_list = Exercice.objects.all()
    liste_dates = Exercice.objects.values_list('date', flat=True)
    liste_valeurs = Exercice.get_list_values()
    return render(request, 'exercice/home.html', locals())

class ExerciceCreate(CreateView):
    model = Exercice
    form_class = ExerciceForm
    template_name = 'exercice/exercice_create_form.html'
    success_url = reverse_lazy('exercice_home')
    
    def get_context_data(self, **kwargs):
        context = super(ExerciceCreate, self).get_context_data(**kwargs)
        context['last_stat'] = Exercice.objects.all()[0]
        return context

class ExerciceUpdate(UpdateView):
    model = Exercice
    form_class = ExerciceForm
    template_name = 'exercice/exercice_create_form.html'
    success_url = reverse_lazy('exercice_home')

class ExerciceDelete(DeleteView):
    model = Exercice
    form_class = ExerciceForm
    template_name = 'exercice/exercice_delete.html'
    success_url = reverse_lazy('exercice_home')



def graph(request):
    #exercice_type_list = ['D (ventre)', 'Q (ventre)', 'D (cote-gauche)', 'Q (cote-gauche)']
    exercice_type_list = ['Deborah','Quentin']
    liste_dates = Exercice.objects.values_list('date', flat=True)
    liste_values = np.array(Exercice.get_list_values()) / 60
    
    
    fig = Figure()
    ax = fig.add_subplot(111)
    #data_df = pd.DataFrame(Exercice.get_list_values(), index=pd.date_range(liste_dates[0], periods=len(liste_dates)), columns=exercice_type_list)
    data_df = pd.DataFrame(liste_values, index=pd.date_range(liste_dates[0], periods=len(liste_values)), columns=exercice_type_list)
    data_df.plot(ax=ax, marker='o')
    canvas = FigureCanvas(fig)
    response = HttpResponse( content_type = 'image/png')
    canvas.print_png(response)
    return response

poc_sport/templates/exercice/exercice_create_form.html
{% extends "base.html" %}

{% block left_nav %}
    <div class="list-group launcher">
        <a href="{% url 'exercice_home' %}">
            <button type="button" class="btn btn-default">
                <span class="glyphicon glyphicon-arrow-left"></span>
            </button>
        </a>
    </div>
{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="row">
            <p>
                {{ form.date.errors }}
                    <label for="{{ form.date.id_for_label }}">Date :</label>
                    {{ form.date }}
            </p>
            <p>
                {{ form.exercice.errors }}
                    <label for="{{ form.exercice.id_for_label }}">Exercice :</label>
                    {{ form.exercice }}
            </p>
            <p>
                {{ form.temps_qt.errors }}
                    <label for="{{ form.temps_qt.id_for_label }}">Temps Quentin : </label>
                    {{ form.temps_qt }}
                    
                    <input type=button id="start_qt" value="START"/>
                    <input type=button id="stop_qt" value="STOP"/>
                    <input type=button id="clear_qt" value="RESET"/>
            </p>
            <p>
                {{ form.temps_db.errors }}
                    <label for="{{ form.temps_db.id_for_label }}">Temps Deborah :</label>
                    {{ form.temps_db }}
                    
                    <input type=button id="start_db" value="START"/>
                    <input type=button id="stop_db" value="STOP"/>
                    <input type=button id="clear_db" value="RESET"/>
            </p>
        </div>
        <div class="row">
            <div class="form-group">
                <input type="submit" value="Submit" />
            </div>
        </div>
    </form>
    
    
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
      <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
      <script>
            $( function() {
              $( "#id_date" ).datepicker();
            } );
    </script>
    <script type="text/javascript">
        /*
        var h1 = document.getElementById('id_temps'),
        start = document.getElementById('start'),
        stop = document.getElementById('stop'),
        clear = document.getElementById('clear'),
        seconds = 0, minutes = 0, hours = 0,
        t;
        
        function add() {
            seconds++;
            if (seconds >= 60) {
                seconds = 0;
                minutes++;
                if (minutes >= 60) {
                    minutes = 0;
                    hours++;
                }
            }           
            h1.value = (hours ? (hours > 9 ? hours : "0" + hours) : "00") + ":" + (minutes ? (minutes > 9 ? minutes : "0" + minutes) : "00") + ":" + (seconds > 9 ? seconds : "0" + seconds);
            timer();
        }
        function timer() {
            t = setTimeout(add, 1000);
        }
        timer();   
        // Start button
        start.onclick = timer;
        // Stop button 
        stop.onclick = function() {
            clearTimeout(t);
        }
        // Clear button
        clear.onclick = function() {
            h1.value = "00:00:00";
            seconds = 0; minutes = 0; hours = 0;
        }
    */
        
        /*
        var compteur_qt = document.getElementById('id_temps_qt'),
        compteur_db = document.getElementById('id_temps_db'),
        seconds = 0, minutes = 0, hours = 0,
        t_qt,
        t_db;
        
        function add(field) {
            seconds++;
            if (seconds >= 60) {
                seconds = 0;
                minutes++;
                if (minutes >= 60) {
                    minutes = 0;
                    hours++;
                }
            }           
            field.value = (hours ? (hours > 9 ? hours : "0" + hours) : "00") + ":" + (minutes ? (minutes > 9 ? minutes : "0" + minutes) : "00") + ":" + (seconds > 9 ? seconds : "0" + seconds);
            timer();
        }
        function timer(t,field) {
            t = setTimeout(add(field), 1000);
        }
        timer();   
        // Start button
        document.getElementById('start_db').onclick = timer(t_db,compteur_db);
        document.getElementById('start_qt').onclick = timer(t_qt,compteur_qt);
        // Stop button
        document.getElementById('stop_db').onclick = function() {
            clearTimeout(t_db);
        }
        document.getElementById('stop_qt').onclick = function() {
            clearTimeout(t_qt);
        }
        // Clear button
        document.getElementById('clear_db').onclick = function() {
            compteur_db.value = "00:00:00";
            seconds = 0; minutes = 0; hours = 0;
        }
        document.getElementById('clear_qt').onclick = function() {
            compteur_qt.value = "00:00:00";
            seconds = 0; minutes = 0; hours = 0;
        }
        //
    </script>
{% endblock %}

poc_sport/templates/exercice/exercice_delete.html
{% extends "base.html" %}

{% block content %}
    <p>You are about to delete the exercice</p>
    <form method="post" action="">
        {% csrf_token %}  <!-- Nous prenons bien soin d'ajouter le csrf_token -->
        <input type="submit" value="Proceed" />
        <a href="{% url "host_list" %}">Cancel</a>
    </form>
{% endblock %}

poc_sport/templates/exercice/home.html
{% extends "base.html" %}

{% block left_nav %}
    <div class="list-group launcher">
        {% block launcher %}
            <h4>Ajouter exercice</h4>
            <a href="{% url 'exercice_create' %}">
                <button type="button" class="btn btn-default" data-toggle="tooltip" data-placement="top" title="add poupinou">
                    <span class="glyphicon glyphicon-plus"></span>
                </button>
            </a>
        {% endblock %}
    </div>
{% endblock %}

{% block title %}Score poupinous{% endblock %}

{% block content %}
    
    <div class="row">
        <div class="col-lg-12">
            <img src="{% url 'exercice_graph' %}"/>
        </div>
    </div>
    
    <table class="table table-bordered table-striped">
        <tr>
            <th>Date</th>
            <th>Exercice</th>
            <th>temps Deborah</th>
            <th>temps Quentin</th>
        </tr>
        {% regroup exercice_list by date as exercices %}
        {% for ex in exercices %}
        <tr>
            <td rowspan="{{ex.list|length}}">
                {{ex.grouper}} <br>
                Quentin : {{ex.get_temps_total_by_date}}<br>
                Deborah : 
            </td>
                {% for type_ex in ex.list %}
                    {% if forloop.counter0 == 0 %}
                        <td>
                            {{type_ex.exercice}}
                            <span style="float: right">
                                <a href="{% url 'exercice_delete' type_ex.id %}">
                                    <button type="button" class="btn btn-default btn-xs" data-toggle="tooltip" data-placement="top" title="delete">
                                        <span class="glyphicon glyphicon-remove"></span>
                                    </button>
                                </a>
                                <a href="{% url 'exercice_update' type_ex.id %}">
                                    <button type="button" class="btn btn-default btn-xs" data-toggle="tooltip" data-placement="top" title="edit">
                                        <span class="glyphicon glyphicon-pencil"></span>
                                    </button>
                                </a>
                            </span>
                        </td>
                        <td>{{type_ex.temps_db}}</td>
                        <td>{{type_ex.temps_qt}}</td>
                    {% else %}
                        <tr>
                            <td>
                                {{type_ex.exercice}}
                                <span style="float: right">
                                    <a href="{% url 'exercice_delete' type_ex.id %}">
                                        <button type="button" class="btn btn-default btn-xs" data-toggle="tooltip" data-placement="top" title="delete">
                                            <span class="glyphicon glyphicon-remove"></span>
                                        </button>
                                    </a>
                                    <a href="{% url 'exercice_update' type_ex.id %}">
                                        <button type="button" class="btn btn-default btn-xs" data-toggle="tooltip" data-placement="top" title="edit">
                                            <span class="glyphicon glyphicon-pencil"></span>
                                        </button>
                                    </a>
                                </span>
                            </td>
                            <td>{{type_ex.temps_db}}</td>
                            <td>{{type_ex.temps_qt}}</td>
                        </tr>
                    {% endif %}
                {% endfor %}
        </tr>
        {% endfor %}
    </table>
    
    {% comment %}
    <table class="table table-bordered table-striped">
        <tr>
            <th>Date</th>
            <th>Exercice</th>
            <th>Deborah</th>
            <th>Quentin</th>
        </tr>
    {% for ex in exercice_list %}
        <tr>
            <td>
                {{ex.date}}
                <span style="float: right">
                    <a href="{% url 'exercice_delete' ex.id %}">
                        <button type="button" class="btn btn-default btn-xs" data-toggle="tooltip" data-placement="top" title="delete">
                            <span class="glyphicon glyphicon-remove"></span>
                        </button>
                    </a>
                    <a href="{% url 'exercice_update' ex.id %}">
                        <button type="button" class="btn btn-default btn-xs" data-toggle="tooltip" data-placement="top" title="edit">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </button>
                    </a>
                </span>
            </td>
            <td>{{ex.exercice}}</td>
            <td>{{ex.temps_db}}</td>
            <td>{{ex.temps_qt}}</td>
        </tr>
    {% endfor %}
    </table>
    {% endcomment %}
    
    
    <br>
{% endblock %}